Commented code and minor tweaks
sam16222/CookBook pull request #60
Opened 2022-10-07 17:57 UTC by kAsrita

2022-10-07 19:25 UTC, sam16222 requested changes

2022-10-07 19:25 UTC, sam16222 commented on frontend/.docz/gatsby-node.js
> +const { get } = require('docz-utils')
Are these files being used?

2022-10-07 20:04 UTC, kAsrita commented on frontend/.docz/gatsby-node.js
> +const { get } = require('docz-utils')
Removed additional files introduced through docz

2022-10-08 13:19 UTC, sam16222 approved these changes

2022-10-08 13:30 UTC, closed without merging